moving_coarsearmadillo_hete_full_SI_rescaled_script;
moving_armadillo_hete_full_SI_rescaled_script;
moving_coarsearmadillo_hete_full_SI_not_rescaled_script;
moving_armadillo_hete_full_SI_not_rescaled_script;
