fname = mfilename;
fname_end = strfind(mfilename,'_p_script');

fname = fname(1:fname_end-1);
meshfiles = {'coarsearmadillo'};
% meshfiles = {'small_bar_h_4.80e-01','small_bar_h_2.50e-01','small_bar_h_2.00e-01'};
% meshfiles = {'coarseoctopus.1'};
parameter_lists = {...
    'dt',[1/100],...
    'T',[5],...
    'solver',{'SemiImplicit_rescaled'},...
    'Y',8e5,...
    'P',0.45,...
    'rho',1e3,...
    'a',0,...
    'b',0.03,...
    'material_type',{'stvk'},...
    'gravity',{'on'},...
    'NMSC',[true],...
    'meshfile',meshfiles,...
    'scene_name',{'unif1'},...
    'eig_modes',50,...
    'fine_meshfile',{'armadillo'},...
    };
% 
% parameter_lists = {...
%     'dt',[1/100],...
%     'T',[5],...
%     'solver',{'SemiImplicit'},...
%     'Y',8e5,...
%     'P',0.45,...
%     'rho',1e3,...
%     'a',0,...
%     'b',0.02,...
%     'material_type',{'stvk'},...
%     'gravity',{'on'},...
%     'NMSC',[false],...
%     'meshfile',meshfiles,...
%     'scene_name',{'hete1'},...
%     }; 

% filename_list = parse_parameter(fname,[],parameter_lists);
% annotation_list = parse_parameter('simulation3D_scene_annotation',[],parameter_lists);
parse_parameter('simulation3D_eigenmodes',[],parameter_lists);
% disp()
