fname = mfilename;
fname_end = strfind(mfilename,'_p_script');

fname = fname(1:fname_end-1);
meshfiles = {'barmesh7','barmesh8','barmesh9','barmesh10'};
% meshfiles = {'small_bar_h_4.80e-01','small_bar_h_2.50e-01','small_bar_h_2.00e-01'};
% meshfiles = {'coarseoctopus.1'};

parameter_lists = {...
    'dt',[1/100],...
    'T',[5],...
    'solver',{'SemiImplicit'},...
    'Y',2e4,...
    'P',0.45,...
    'rho',1e3,...
    'a',0,...
    'b',0.01,...
    'material_type',{'stvk'},...
    'gravity',{'off'},...
    'NMSC',[false],...
    'meshfile',meshfiles...
    }; 

filename_list = parse_parameter(fname,[],parameter_lists);
annotation_list = parse_parameter('simulation3D_scene_annotation',[],parameter_lists);
